export const INTERNAL_FETCH_REQUESTED = "INTERNAL_FETCH_REQUESTED";
export const INTERNAL_FETCH_SUCCEEDED = "INTERNAL_FETCH_SUCCEEDED";
export const INTERNAL_FETCH_FAILED = "INTERNAL_FETCH_FAILED";
export const USER_FETCH_REQUESTED = "USER_FETCH_REQUESTED";
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";
export const MESSAGE_MAPPING_FETCH_REQUESTED =
	"MESSAGE_MAPPING_FETCH_REQUESTED";
export const MESSAGE_MAPPING_FETCH_SUCCEEDED =
	"MESSAGE_MAPPING_FETCH_SUCCEEDED";
export const MESSAGE_MAPPING_FETCH_FAILED = "MESSAGE_MAPPING_FETCH_FAILED";
export const PARTNER_FETCH_REQUESTED = "PARTNER_FETCH_REQUESTED";
export const PARTNER_FETCH_SUCCEEDED = "PARTNER_FETCH_SUCCEEDED";
export const PARTNER_FETCH_FAILED = "PARTNER_FETCH_FAILED";
export const USER_TABLE = "sys_user";
export const NO_DATA = "No Data";
export const PREVIEW_RECORD = "PREVIEW_RECORD";
export const OPEN_USER_DETAILS = "OPEN_USER_DETAILS";
export const CARD_CLICKED = "NOW_CARD#CLICKED";
export const BUTTON_HEADER_CLICKED = "NOW_CARD_HEADER#ACTION_CLICKED";
