export const MAPPING_FIELDS_FETCH_REQUESTED = "MAPPING_FIELDS_FETCH_REQUESTED";
export const MAPPING_FIELDS_FETCH_SUCCEEDED = "MAPPING_FIELDS_FETCH_SUCCEEDED";
export const MAPPING_FIELDS_FETCH_FAILED = "MAPPING_FIELDS_FETCH_FAILED";
export const NO_DATA = "No Data";
export const CLOSE_MAPPING = "CLOSE_MAPPING";
