export const INTEGRATION_MESSAGE_LOAD_REQUESTED =
	"INTEGRATION_MESSAGE_LOAD_REQUESTED";
export const INTEGRATION_MESSAGE_LOAD_SUCCEEDED =
	"INTEGRATION_MESSAGE_LOAD_SUCCEEDED";
export const INTEGRATION_MESSAGE_LOAD_STARTED =
	"INTEGRATION_MESSAGE_LOAD_STARTED";
export const INTEGRATION_MESSAGE_LOAD_FAILED =
	"INTEGRATION_MESSAGE_LOAD_FAILED";
export const FETCH_ITEM_REQUESTED = "FETCH_ITEM_REQUESTED";
export const FETCH_ITEM_SUCCEEDED = "FETCH_ITEM_SUCCEEDED";
export const FETCH_ITEM_FAILED = "FETCH_ITEM_FAILED";
export const URL_TABLE_INTEGRATION_MESSAGE =
	"/api/now/table/x_554832_integrati_integration_message";
export const URL_CURRENT_USER = "api/now/ui/user/current_user";
export const CURRENT_CARD_CHANGED = "CURRENT_CARD_CHANGED";
export const NO_DATA = "No Data";
export const NOW_CARD_ACTION_RECORD_DETAIL =
	"NOW_CARD_ACTIONS#RECORD_DETAIL_CLICKED";
export const NOW_CARD_ACTION_MAPPING_FIELD =
	"NOW_CARD_ACTIONS#MAPPING_FIELD_CLICKED";
export const SHOW_RECORD = "SHOW_RECORD";
export const CLOSE_RECORD_CLICKED = "CLOSE_RECORD_CLICKED";
export const SHOW_MAPPING_FIELD = "SHOW_MAPPING_FIELD";
export const CLOSE_MAPPING_CLICKED = "CLOSE_MAPPING_CLICKED";
export const REFRESH_BUTTON_CLICKED = "NOW_BUTTON_ICONIC#CLICKED";
