export const CALLER_FETCH_REQUESTED = "CALLER_FETCH_REQUESTED";
export const CALLER_FETCH_SUCCEEDED = "CALLER_FETCH_SUCCEEDED";
export const CALLER_FETCH_FAILED = "CALLER_FETCH_FAILED";
export const ASSIGNMENT_GROUP_FETCH_REQUESTED =
	"ASSIGNMENT_GROUP_FETCH_REQUESTED";
export const ASSIGNMENT_GROUP_FETCH_SUCCEEDED =
	"ASSIGNMENT_GROUP_FETCH_SUCCEEDED";
export const ASSIGNMENT_GROUP_FETCH_FAILED = "ASSIGNMENT_GROUP_FETCH_FAILED";
export const ASSIGN_TO_FETCH_REQUESTED = "ASSIGN_TO_FETCH_REQUESTED";
export const ASSIGN_TO_FETCH_SUCCEEDED = "ASSIGN_TO_FETCH_SUCCEEDED";
export const ASSIGN_TO_FETCH_FAILED = "ASSIGN_TO_FETCH_FAILED";
export const NO_DATA = "No Data";
export const PREVIEW_RECORD = "PREVIEW_RECORD";
export const CLOSE_RECORD = "CLOSE_RECORD";
export const GET_ATTACHMENT_LIST_URL =
	"/api/x_554832_integrati/get_attachment/get_attachment_for_record?table_sys_id=:class_id&table_name=incident";
export const ATTACHEMENT_FETCH_REQUESTED = "ATTACHEMENT_FETCH_REQUESTED";
export const ATTACHEMENT_FETCH_SUCCEEDED = "ATTACHEMENT_FETCH_SUCCEEDED";
export const ATTACHEMENT_FETCH_FAILED = "ATTACHEMENT_FETCH_FAILED";
export const ATTACHEMENT_LIST_FETCH_REQUESTED =
	"ATTACHEMENT_LIST_FETCH_REQUESTED";
export const ATTACHEMENT_LIST_FETCH_SUCCEEDED =
	"ATTACHEMENT_LIST_FETCH_SUCCEEDED";
export const ATTACHEMENT_LIST_FETCH_FAILED = "ATTACHEMENT_LIST_FETCH_FAILED";
export const ATTACHEMENT_FETCH_STARTED = "ATTACHEMENT_FETCH_STARTED";
export const ATTACHEMENT_LIST_FETCH_STARTED = "ATTACHEMENT_LIST_FETCH_STARTED";
